### PR TITLE
Update upstream parity

### PR DESCRIPTION
**Pull request by s1na**
This PR updates the `parity-ethereum` to v2.3.3, and fixes the breaking api changes that have happened. Build doesn't fail anymore, but I didn't know how to test it!

### CODE REVIEW

**Comment by s1na** [comment]
Updated the build script to use `chisel` instead of `wasm-gc`, and replaced `stat -f%z` with `wc -c` which is more portable (`stat` didn't work for me).

I was also able to instantiate the module from js.

**Comment by axic** [comment]
It seems upstream is so unstable that now it doesn't compile anymore:
```
    Updating git repository `https://github.com/ewasm/ewasm-rust-api`                                                                                                    
    Updating git repository `https://github.com/paritytech/parity-common`                                                                                                
error: no matching package named `patricia-trie` found                                                                                                                   
location searched: https://github.com/paritytech/parity-common
required by package `vm v0.1.0 (/Users/alex/Projects/runevm/parity-ethereum/ethcore/vm)`
    ... which is depended on by `runevm v0.1.0 (/Users/alex/Projects/runevm)`
```

**Comment by s1na** [comment]
I did a fresh clone to test and it seems to work. Is your submodule on https://github.com/paritytech/parity-ethereum/commit/3b9b1a8f147f870878e88d5edf7e5fca74988c3e?

**Comment by axic** [comment]
My bad, it did work on another fresh install.

**Pull request merged**
